### ISSUE TITLE
ERR wrong number of arguments for 'info' command

### ISSUE THREAD

**Issue by iefserge** [NodeRedis/node_redis#1009] opened 2016-03-16 15:09 UTC
Hi, thank you for the great library! There is an error I'm getting when using the latest version (2.5.1), but at the same time 2.4.2 works fine.

* **Version**: 2.5.1
* **Platform**: Node.js 5.4.1 (but I think others are affected as well)
* **Description**: stack trace below
```
Error: Ready check failed: ERR wrong number of arguments for 'info' command
    at JavascriptReplyParser.parseResult (/Users/serge/test/node_modules/redis-parser/lib/javascript.js:86:16)
    at JavascriptReplyParser.tryParsing (/Users/serge/test/node_modules/redis-parser/lib/javascript.js:116:21)
    at JavascriptReplyParser.run (/Users/serge/test/node_modules/redis-parser/lib/javascript.js:130:22)
    at JavascriptReplyParser.execute (/Users/serge/test/node_modules/redis-parser/lib/javascript.js:111:10)
    at Socket.<anonymous> (/Users/serge/test/node_modules/redis/index.js:223:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by BridgeAR** [comment] 2016-03-16 15:17
Duplicate of #1008

**Closed by BridgeAR** 2016-03-16 15:17 UTC

**Comment by BridgeAR** [comment] 2016-03-16 15:31
@iefserge thanks for your report. Would you be so kind and run your code with 2.5.0 and reply if that works and what redis version do you use?

**Comment by BridgeAR** [comment] 2016-03-16 23:06
This should work properly again in 2.5.2 and it should not have broken anyone's code. Sorry for the inconvenience.
