### ISSUE TITLE
usage with node cluster causes intermittent latency issues

### ISSUE THREAD

**Issue by torra** [NodeRedis/node_redis#875] opened 2015-10-01 21:45 UTC
We run ec2 instances using node cluster, with ~5 workers per instance. We were using an old version (0.10.3), and when we tried to upgrade we started seeing timeouts on the load balancer. Here is what I noticed:
- disabling cluster fixes the issue
- leaving cluster enabled, but only using one worker fixes the issue
- reverting back to 0.10.3 fixes the issue (update: 0.12.1 and 1.0.0 also seem to work fine)

Unfortunately I don't have time to dig much deeper, but something since 0.10 seems to not play nice with node cluster.

Any thoughts on what would cause such behavior?

Update with some more info:
- We talk to several different redis servers, both locally and remote. Locally we talk over a unix socket
- We are running redis 3.0.3
- On our local redis server, we do `get`, `hmget`, `hgetall`, `smembers`, `sunion`, and `sinter` operations
- On our remote servers, we do `zrange` and `zrevrange` operations

- I have been testing a bit with both node 0.10.40, but mostly (and currently only) 4.1.1

**Comment by BridgeAR** [comment] 2015-10-02 18:36
@torra would you be so kind and also test 0.12.1? And could you give me some insights into your code?

**Comment by torra** [comment] 2015-10-02 20:07
0.12.1 and 1.0.0 both work fine

Our code does mostly `get`, `hmget`, and `hgetall` operations, along with some `zrange` and `zrevrange`. See update above for more details

**Comment by BridgeAR** [comment] 2015-10-02 20:13
@torra did you check the breaking changes and the difference how reconnecting is handled now? And could you test v.2.1 too? I just released it about an hour ago.

**Comment by torra** [comment] 2015-10-02 20:34
@BridgeAR which difference in reconnecting specifically are you referring to? I did review the breaking changes, and while testing everything seems(ed) fine. We log all errors, disconnects, etc. anyways, and I haven't seen a sign of anything like that. 

This only occurs when using node cluster, so it seems like something specific to that. I have also not been able to even reproduce the problem outside of production. I can only see that some requests end up taking abnormally long, hitting our load balancer timeout (60s) - I haven't been able to actually see a request trigger the issue.

I can't test with 2.1 right now, but early next week I can give it a shot (probably Tuesday).

I would love to try and come up with a simple way to reproduce the problem, but unfortunately I haven't had the time. It would be great to hear from others using nodes cluster module in production.

**Comment by zaggino** [comment] 2015-10-07 04:34
Hi guys, just my two bits in, I have been running into this even without using cluster. Seems like throwing multiple parallel requests at redis is causing this. I've reverted to `1.0.0` to see if it fixes my problem. I don't have an exact scenario to reproduce but I'll try to get back to this if I find something out.

**Comment by bcoe** [comment] 2015-10-07 06:55
@zaggino anything in particular requests that are causing the issue, can you produce this problem with something simple like a sequence of `get`/`set` operations?

**Comment by BridgeAR** [comment] 2015-10-07 10:52
@torra @zaggino what parser do you use? @zaggino could you show the code that failed in your case? It might be good to look at that even if it's not reproducible with just that code.

**Comment by zaggino** [comment] 2015-10-07 11:10
Not sure what you mean by `parser` but in the project the single most used function is definitely this:
```
redis.RedisClient.prototype.setJsonAsync = function (key, value) {
  return this.setAsync(key, typeof value === 'object' ? JSON.stringify(value) : value);
};
```
and its reverse `getJsonAsync`. We use `Bluebird.promisifyAll(redis.RedisClient.prototype);` as above suggests.

We don't really use any advanced operations in the project, listing them all: `get` `set` `setex` `exists` `del`.

After reverting to `1.0.0` the incident didn't seem to happen for the last 6 hours, but I don't have time to spare investigating this further as we are before important milestone. I'll definitely get back to this later when the time will be less of a issue.

**Comment by BridgeAR** [comment] 2015-10-07 11:16
@zaggino do you use the hiredis or the javascript parser? Hiredis is a native module that you have to install separately to node_redis and the javascript parser is built in and will be choosen if hiredis is not present.

**Comment by zaggino** [comment] 2015-10-07 11:17
Right, we don't use `hiredis`, might be a good thing to try that out if it solves the problem with `2.x` then.

**Comment by BridgeAR** [comment] 2015-10-07 11:19
That would be great

**Comment by BridgeAR** [comment] 2015-10-08 11:09
@torra @zaggino would you be so kind and both test the hiredis parser? My best guess is, that it might have something to do with the js parser.
And what node version do you use?

**Comment by zaggino** [comment] 2015-10-08 11:25
I won't be able to test before next week on our servers, but the node is `4.1.0`

**Comment by torra** [comment] 2015-10-08 17:56
@BridgeAR : 

With 2.1 I see the same issue.

I have been testing a bit with both node 0.10.40 and node 4.1.1. Currently I am focusing on testing with only 4.1.1. (added to original issue).

We actually switched from using the hiredis parser to the built in javascript parser a few months back, and I just tested with hiredis again and it does seem to fix the problem (node 4.1.1, redis@2.1.0).

**Comment by BridgeAR** [comment] 2015-10-09 00:45
That's what I thought. Seems like our tests do not cover all possible outcomes and I was to eager while refactoring the js parser. I'll fix that in 2.2.1.

@torra could you provide me with a short code part that fails? That way you'd do me a big favor, since writing a test on that code part is going to be easier than having to come up with something on my own.

**Comment by bcoe** [comment] 2015-10-09 05:06
@zaggino is there anything else interesting you're doing? how many redis clients do you instantiate just the one?

What's the failure state that you're seeing, an attempt to set JSON hanging for a long period of time?

**Comment by torra** [comment] 2015-10-09 19:32
@BridgeAR I don't think I'm going to have a chance today, but I'll try to do that either this weekend or early next week. We use redis pretty heavily, and since I haven't been able to reproduce the problem outside of production it's hard for me to narrow it down to a small piece of code at the moment.

**Comment by BridgeAR** [comment] 2015-10-10 01:53
@torra @zaggino the issue should be fixed on latest master. Please try that :)

**Comment by elizehavi** [comment] 2015-10-18 07:52
@torra, I'm having similar problems with my ec2 instances that connect to the elasticache redis.

Does the last update fix your latency problems?

**Comment by eli-zehavi** [comment] 2015-10-18 07:54
@torra, I'm having similar problems with my ec2 instances that connect to the elasticache redis.

Does the last update fix your latency problems?

**Comment by torra** [comment] 2015-10-19 14:35
@BridgeAR I apologize for the slow feedback. I just tested with 2.2.5 and I have the same issue.

**Comment by BridgeAR** [comment] 2015-10-19 15:06
@torra did you test the hiredis parser too?

**Comment by torra** [comment] 2015-10-19 15:23
Just tried it, using the hiredis parser solves the problem still. We are also on node 4.2.1 now

**Comment by elizehavi** [comment] 2015-10-19 15:25
@torra, solves or doesn't solve?

**Comment by torra** [comment] 2015-10-19 15:26
Clarified the comment :)

**Comment by BridgeAR** [comment] 2015-10-19 15:27
@torra I'm going to push a commit later on and it would be great if could test that fix before I release a new version :)

**Comment by torra** [comment] 2015-10-19 15:27
Sure @BridgeAR - I'll keep an eye out for the commit

**Comment by BridgeAR** [comment] 2015-10-20 08:52
@torra please try https://github.com/NodeRedis/node_redis/tree/parser

While further analysing the parser I found what I missed in my last fix and it should work now.

**Comment by torra** [comment] 2015-10-20 13:42
@BridgeAR This also does not fix the problem.

I'm not sure if this is the best approach to narrowing down the issue. I'll try to spend some time this week isolating the issue for others to reproduce, but please understand this is not a high priority for me. I appreciate the responsiveness and effort in trying to fix it.

**Comment by BridgeAR** [comment] 2015-10-20 13:54
I can't see any changes in the parser since v.1.0 that might break anything besides the ones I reverted. I could rewrite the parser in a way that it's working just the same as the one used in v.1.0 but that it works on v.2.

The js parser has the issue that it can't handle big files right now (the parser time is exponantial to the chunks for n chunks with size > 2^16) but other than that everything should work fine as I see it :/

**Comment by eli-zehavi** [comment] 2015-10-21 21:59
@BridgeAR, to use the hiredis parser should I only need to install it as package on the project and then node_redis will use it, or should it require it in my code before require node_redis?

**Comment by BridgeAR** [comment] 2015-10-21 22:47
@eli-zehavi Hiredis is the default parser if it's present. If you install the parser it'll automatical be used.

**Comment by eli-zehavi** [comment] 2015-10-21 22:58
Ok, I've installed hiredis about 1.5 hours ago and, unfortunately, the latency problems didn't disappear. I'll try to run it with only 1 worker in the cluster module to verify this is the problem.

**Comment by BridgeAR** [comment] 2015-10-27 10:35
@torra @zaggino i finally found a reproducible test that could result in a timeout with the js parser. Would you be so kind and test #903? :)

If this does not fix the issue, please uncomment [line 113 (the debug statement)](https://github.com/NodeRedis/node_redis/blob/851dd8720684ed084e069f9d7659b9e736033fdc/index.js#L113) and activate the debug mode with `NODE_DEBUG=redis`. That way you should see all results passed back to you and this would be helpful to debug this issue. I forgot about that debug statement earlier.

**Comment by torra** [comment] 2015-10-27 15:37
@BridgeAR that PR does indeed seem to fix the problem for me. Thanks for figuring this out, despite my lack of helpfulness. I'll keep an eye out for a new release

**Closed** 2015-10-27 16:28 UTC
Labels: bug
