### ISSUE TITLE
Modules with sentinel and cluster support

### ISSUE THREAD

**Issue by AVVS** [NodeRedis/node_redis#741] opened 2015-04-18 22:38 UTC
I've seen a number of modules, which had been trying to do something in regards to this, but they are either incomplete and barely maintained, or use conventions I'm not very fond of.

https://github.com/thunks/thunk-redis - this looks like the only working cluster implementation

Sentinels:

https://github.com/gitterHQ/node-redis-sentinel-client, which is a fork of
https://github.com/DocuSignDev/node-redis-sentinel-client and
https://github.com/ortoo/node-redis-sentinel

So the question is who is using what, is there any progress being done on improving this module with much needed support of the these features - there are issues for that ranging from 2013 to mid 2014, but soon its mid of 2015 and, well, redis-cluster has finally seen it's first release... Would appreciate if some1 can enlighten me of the latest developments in these areas.

**Comment by luin** [comment] 2015-04-19 16:08
I've built another redis client [ioredis](https://github.com/luin/ioredis) that is used in our company. It supports sentinel and cluster(experimental yet).

**Comment by chisleu** [comment] 2015-04-20 15:12
* more and more people are using this as the default redis integration (330k downloads last week)
* the latest redis incorporated redis cluster changes (tighter sentinel integration)

I think an attempt should be made to integrate cluster/sentinel.

I have written this in other languages and I'm familiar with node. Coffee seems straight forward.

If no one else is on this already, and the maintainer is interested in adding the functionality, I would be happy to help. It shouldn't be a major change for the native redis client.

**Comment by smithandweb** [comment] 2015-04-21 14:54
+1 Please implement

**Comment by kadishmal** [comment] 2015-04-23 09:38
@luin thanks for linking to **ioredis**. Didn't know about it. Will give it a try. I wonder if the `express-session` module works properly with `ioredis`?

**Comment by luin** [comment] 2015-04-23 10:03
@kadishmal The only differences between ioredis and redis in terms of API are constructor and transaction, so it's not hard to migrate your code from redis to ioredis. However if you are using a third-party library that replies on redis(e.g. express-session, connect-redis), I don't think it's necessary to migrate them since you can use ioredis and redis in a same app.

**Comment by kadishmal** [comment] 2015-04-23 14:25
I see. I will take a look. Thank you.

**Comment by wavded** [comment] 2015-04-23 15:17
Hi, I maintain `connect-redis` and there is an option to pass in a redis `client`, as long as the api supports `get` `set` `setex` and `del` it should work.  I haven't tried it yet but if it does I'll add `ioredis` as another client you can pass as people have been asking for sentinel and cluster support.

**Comment by luin** [comment] 2015-04-23 15:22
@wavded That's cool! I'll do some testing this weekend and will let you know if it works.

**Comment by wavded** [comment] 2015-04-23 15:23
Sweet!

**Comment by BridgeAR** [comment] 2015-09-23 23:06
@chisleu would you still be up to implement either or both features? :) I'd highly appreciate that

**Comment by BridgeAR** [comment] 2015-09-23 23:07
Duplicate of #574  and #302

**Comment by chisleu** [comment] 2015-09-23 23:07
@BridgeAR I moved to ioredis, which seems to support these already.

**Closed by BridgeAR** 2015-09-23 23:07 UTC
Labels: Feature Request
