### ISSUE TITLE
Node app does nothing after 5 to 10 minute being idle with redis

### ISSUE THREAD

**Issue by mpsiva89** [NodeRedis/node_redis#1231] opened 2017-05-04 04:56 UTC
* **Version**:
node_redis - 2.7.0
redis - 3.2.8
* **Platform**:
Node - 6.9.0 spawned by Docker (OS - Ubuntu 14.04, Azure)
Redis - 3.2.8 Ubuntu 14.04

```
var express = require('express');
var app = express();
var redis = require('redis');

redis_client = redis.createClient(6379, 'remoteRedisEndpoint');

app.get('/', function (req, res) {
  redis_client.get('testdata', function(err, data) {
    if(err) {
    	console.log(err)
    } else {
      res.send(JSON.parse(data));
    }
  });  
});

app.listen(3000, function () {
  console.log('Example app listening on port 3000!')
});
```

Above app works fine when we send a continuous request to the app. But if the app is idle for 5 minutes and the immediate request after that does nothing. It just hangs.

Above issue happens only when we hit the remote redis which is in Azure. But if we use the replica of the redis (with same configuration) in local environment, everything is fine.

Did anyone face this issue?

**Comment by stockholmux** [comment] 2017-05-04 10:04
If the issue is only happening with a remote Redis server and is fine with your local Redis instance, it isn't really an issue with this Node module.

Since it isn't related to the module, I'm going to close this issue. But regarding your problem, you might want take a look at your idle settings either in your SSH tunnel or firewall. Either issue could cause a connection to hang (but it could be something in your Azure settings also - hard to tell). You could also use the `client.on(...)` [connection events](https://github.com/NodeRedis/node_redis#connection-and-other-events) to help debug this issue if it's something else. 

Best of luck.

**Closed by stockholmux** 2017-05-04 10:04 UTC

**Comment by parthroy** [comment] 2024-04-11 14:11
I am facing the same issue
