### ISSUE TITLE
client.get hangs and never calls callback

### ISSUE THREAD

**Issue by lambertsteven** [NodeRedis/node_redis#902] opened 2015-10-26 23:06 UTC
I'm currently experiencing some odd behavior where every so often, some of the calls to `client.get` hang and the callback function is never called. I've turned on `NODE_DEBUG=redis`, but the logs aren't showing me anything more helpful, just that a call to `client.get` was made

```
Send barreleye.redistogo.com:[port] id 1: *2
$3
get
$70
[key]
```

I have a ton of debug logs that would fire if the callback comes back, but instead nothing happens and Heroku logs an H12 for a 30 second timeout.

```
heroku[router] at=error code=H12 desc="Request timeout" method=GET path="/all" host=[app] request_id=[id] dyno=web.2 connect=0ms service=30001ms status=503 bytes=0
```

Here is what my code looks like

```js
debug(key + ": Checking session in redis");
client.get(key, function(err, response) {
  if (err) {
    debug(key + ": Client.get err=" + err);
  }

  // Cache hit
  if(response) {
    debug(key + ": Cache hit=" + response);
    // handle valid cache
  }

  debug(key + ": No response found");
}
```

Any idea what would cause `client.get` to not call the callback? If it helps I'm using Heroku and Redis To Go, and our Redis instance appears to be healthy, using under the limit memory and connections.

**Comment by BridgeAR** [comment] 2015-10-26 23:45
@lambertsteven what parser do you use? I guess this might be a duplicate of #875 

If the hiredis parser fixes your issue: do you have a reproducible test case? That would be really helpful! I was not able to reproduce that issue yet.

**Comment by lambertsteven** [comment] 2015-10-27 01:39
Unfortunately, being able to reproduce the problem is one of our biggest problems. It doesn't happen consistently, and it seems to happen after about an hour or so after restarting the app. Restarting the app seems to clear the issues, but they always come back. It doesn't matter if the request rate is low or high at the time, its about the same amount of chance that the call will hang.

I don't think we're using the hiredis parser, so I guess that means we're using the javascript parser. It looks like this might be related to #875, but it's hard to tell at first glance since we only use `client.get` and `multi.set/exec`.

We're using redis 2.2.5.

**Comment by BridgeAR** [comment] 2015-10-27 10:25
@lambertsteven your issue should be resolved with #903. Would you be so kind and verify that?

**Closed** 2015-10-27 16:28 UTC

**Comment by lambertsteven** [comment] 2015-10-27 16:47
Verifying now, will let you know if it fixed the problem. Thanks for looking into this for us.

**Comment by lambertsteven** [comment] 2015-10-27 23:19
The problem doesn't seem to be resolved, we're still getting intermittent timeouts on `client.get`. We'll use the hiredis parser tomorrow and see if that resolves the issue.

**Comment by BridgeAR** [comment] 2015-10-28 00:04
@lambertsteven hm, strange. Please uncomment [this line](https://github.com/NodeRedis/node_redis/blob/851dd8720684ed084e069f9d7659b9e736033fdc/index.js#L113) and see if you get any return values.

**Comment by lambertsteven** [comment] 2015-10-29 19:24
Alright, so we finally resolved the issue (we hope). We had some code that was using `cache = client.multi()`, and just using it to call `cache.set(key, value)` and `cache.expire(key, ttl)`, then calling `cache.exec()`. This was then throwing an error once in a while in our `client.get` calls that would say that multi calls cant be nested, and also causing the redis cache to put the value `QUEUED` into the database instead of the value we expected. It only manifested itself after an hour or so of heavy use. Thanks for working on this, as I'm sure your fix helped solve the problem.

**Comment by lakshman53** [comment] 2018-09-30 18:10
multi has multiplied my complications :)
