### ISSUE TITLE
 getting error 'ReplyError: ERR syntax error' even though I am sending  array of strings to set, and data is getting set also .

### ISSUE THREAD

**Issue by mamta-dhaka** [NodeRedis/node_redis#1485] opened 2020-01-08 15:50 UTC
getting 'ReplyError: ERR syntax error' error even though data is getting set,
await this.msetAsync(['key', 'data']);
can someone help?

**Comment by BridgeAR** [comment] 2020-02-05 08:15
There are tests for this command and those pass. You could check the logs in debug mode to see that everything works as expected and the error might contain more information that might be valuable.

It is difficult to know what exactly happens on your side, since it's not just the client itself being involved and the code example can't be run on its own.

I am closing this, since it's very likely not a bug in the client itself.

**Closed by BridgeAR** 2020-02-05 08:15 UTC
