### ISSUE TITLE
BRPOP receives INFO response on disconnect/reconnect

### ISSUE THREAD

**Issue by cody-greene** [NodeRedis/node_redis#898] opened 2015-10-23 22:09 UTC
```javascript
/**
 * redis-bug.js
 * Steps:
 * - node@4.0.0
 * - redis@2.2.5
 * - $ docker start redis 
 * - $ node redis-bug.js
 * - $ docker stop redis
 * - redis.on('error', ...)
 * - $ docker start redis
 * - brpop callback recieves INFO response:
 *   # Server
 *   redis_version:3.0.3
 *   ...
 */
'use strict';
const REDIS_URI = 'redis://192.168.59.103:9031'
let wasConnected = false
let redis = require('redis')
  .createClient(REDIS_URI, {retry_max_delay: 30000})
  .on('error', function (err) {
    let isConnected = redis.connected
    // Omit repeated reconnection attempts
    if (isConnected || (!isConnected && wasConnected))
      console.log(new Error(err.message).stack)
    wasConnected = isConnected
  })
  .on('ready', function () {
    wasConnected = true
    console.log('redis connected')
  })

redis.brpop('my-list', 5, function (err, res) {
  if (err) console.log('brpop err:', err.stack)
  else console.log(res)
  redis.quit()
})
```

It looks like BRPOP is still in the `command_queue` when performing the ready check after reconnecting. When the response to INFO comes back: BRPOP is shifted off `command_queue` and that callback gets the response instead. See [here](https://github.com/NodeRedis/node_redis/blob/v.2.2.5/index.js#L585)

**Comment by BridgeAR** [comment] 2015-10-25 11:45
@cody-greene the issue here is with the blocking statement. The command was already fired, but the request was not yet answered. That way the command is still in the command_queue while reconnecting. 

While analyzing the issue further I realized that you can't rely on the result of any fired command that has not yet returned before the connection got lost. We just can't tell if the command was processed or not before the server went down / was not reachable anymore.

So the only way to fix this is likely to reject all still running commands with a message that node_redis can't tell if the command was processed after a connection got lost. And since the command could have altered things, we should not just process the same command again (e.g. incr).

@NodeRedis/contributors please also have a look at this, as I have the feeling that this is something very important.

**Comment by amit777** [comment] 2015-10-26 03:14
is this a recently introduced issue?

**Comment by stockholmux** [comment] 2015-10-26 13:41
@BridgeAR I couldn't recreate the issue. From the descriptions, it only has to do with server connection loss while the command queue is not empty - is that right? 

I can see where it could cause a mess any way it is cut - if the user has non-idempotent commands in the queue and the connection is lost - if we err out then the problem is just deferred to the program.

**Comment by BridgeAR** [comment] 2015-10-26 14:22
@amit777 yes, this is a regression introduced in v.2.0.0. It slipped through while refactoring the reconnect logic including the offline queue. I have a fix local and the next version is going to reject any command that is not yet answered when the connection is lost.

@stockholmux I think this is not really deferred to the program. In my opinion it is the only place where someone might be able to decide what to do with these commands. The best node_redis could do is to add a option to retry all commands that where fired earlier, but only if the developer wants this.

**Comment by amit777** [comment] 2015-10-26 15:30
@BridgeAR thanks. That default behavior sounds good.. We can then process the reject how we want to.

**Comment by BridgeAR** [comment] 2015-10-28 23:02
Fixed on latest master. All commands that are still in the command queue while a connection is lost are now rejected. So this won't be an issue anymore.

**Closed by BridgeAR** 2015-10-28 23:02 UTC
Labels: bug
