### ISSUE TITLE
Feature request: offline_queue bounds

### ISSUE THREAD

**Issue by ryanwe** [NodeRedis/node_redis#1039] opened 2016-04-19 21:37 UTC
* **Version**: `node_redis: 2.6.0-1` `redis_version: 3.0.7`
* **Platform**: Node.js 0.12
* **Description**:  (see below)

The `offline_queue` is great since it allows redis client consumers to operate normally while the redis client is connecting and reconnecting. But we recently ran into an issue when our redis db was unavailable for long enough that this unbound queue (including un-dispatched callbacks) backed up so much that it used up too much memory and brought down the whole node.js processes. As a quick fix, we now set `enable_offline_queue = false` when creating redis clients. But this means that any minor blip in connectivity with redis causes errors.

I think the ideal solution is something in the middle. It would be great if we could continue to use the `offline_queue` but have a cap on either the number of `OfflineCommand`s that can go into the queue before errors are sent to the callbacks right away, or set a timeout for `OfflineCommand`s to wait before passing errors to their callbacks.

[gitter]: https://gitter.im/NodeRedis/node_redis?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by ryanwe** [comment] 2016-04-19 21:39
If you think either (or both) of these solutions would be a useful, I'd be happy to help out and post a PR.

**Comment by BridgeAR** [comment] 2016-04-21 02:16
Duplicate of #932

This is definitely something that has to be implemented. I already thought a couple of times of solutions but neither was a really good fix so far.

**Closed by BridgeAR** 2016-04-21 02:16 UTC
