### ISSUE TITLE
Possible regression: simultaneous multis will not call back

### ISSUE THREAD

**Issue by barn3y** [NodeRedis/node_redis#889] opened 2015-10-13 21:38 UTC
With 2.1.0, you could run two multis simultaneously and still have multi.exec call back.

In 2.2.0, multi.exec will not call back if two multis are in progress on the same connection at the same time.

Test case: https://gist.github.com/barn3y/b838cbed93042da24ca0

Sample results under 2.1.0:

    $ node simultaneous_multi.js
    exec multi 1
    exec multi 2
    multi 1 complete
    multi 2 complete
    <process ends>

Sample results under 2.2.0:

    $ node simultaneous_multi.js
    exec multi 1
    exec multi 2
    <process does not end>

**Comment by BridgeAR** [comment] 2015-10-13 21:57
Hm, I see. I thought about something like that just yesterday after releasing 2.2 and I have to check a couple of things. I'm uncertain if this was fully supported earlier, as the results might get mixed up under some conditions.

**Comment by BridgeAR** [comment] 2015-10-13 22:12
@barn3y I just tried your gist and a couple of different similar actions and all worked for me. What node version do you use?

**Comment by barn3y** [comment] 2015-10-13 22:14
Interesting! Admittedly I'm still on v0.10.38

**Comment by barn3y** [comment] 2015-10-13 22:20
That's it - I tried under 0.12.2 and it worked

**Comment by BridgeAR** [comment] 2015-10-13 22:21
I'll have a closer look at it.

**Comment by barn3y** [comment] 2015-10-13 23:41
I tried my test case again under node 0.10.38 on Mac OS 10.10.5, still no callbacks. Here's the output with NODE_DEBUG=redis on:

    $ NODE_DEBUG=redis node simultaneous_multi.js
    Hiredis parser not installed.
    exec multi 1
    Queueing multi for next server connection.
    Queueing set for next server connection.
    Queueing exec for next server connection.
    exec multi 2
    Queueing multi for next server connection.
    Queueing set for next server connection.
    Queueing exec for next server connection.
    Stream connected 127.0.0.1:6379 id 1
    Using default parser module: javascript
    Checking server ready state...
    Send 127.0.0.1:6379 id 1: *1
    $4
    info

**Comment by BridgeAR** [comment] 2015-10-13 23:57
True, that's even another issue than the one that I just fixed. The issue is only occuring because you're not yet ready :) Fix is incoming in a few minutes.

**Comment by barn3y** [comment] 2015-10-14 00:00
Amazing! Thank you very much!

**Closed** 2015-10-14 00:25 UTC
Labels: bug, fixed / done

**Comment by BridgeAR** [comment] 2015-10-14 00:27
@barn3y The issue should be fixed now. Would you be so kind and test the master right quick?

**Comment by barn3y** [comment] 2015-10-14 00:48
$ node simultaneous_multi.js
    exec multi 1
    exec multi 2
    multi 1 complete
    multi 2 complete

Yep working!

**Comment by BridgeAR** [comment] 2015-10-14 00:51
:) Thx
