### ISSUE TITLE
Redis performance issues

### ISSUE THREAD

**Issue by JamesJGoodwin** [NodeRedis/node_redis#1478] opened 2019-12-12 20:00 UTC
* **Version**: 
`redis-server`: **4.0.9** 
`node-redis`: **2.8.0**
* **Platform**: NodeJS 13 on Windows 10 and NodeJS 12 on Ubuntu 18.04
* **Description**: I'm currently stuck with solving an issue with Redis performance in my project. Recently I've decided to stress-test my web application and found out that performance starts degrade even with 10 concurrent requests. I have tested every part of my application until I came all the way down to Redis. Here's my code example:

```typescript
import Redis from 'redis'
import { promisify } from 'util'

const redis = Redis.createClient()
const redisGetAsync = promisify(redis.get).bind(redis)

const perf = performance.now()
const cachedPopulars: string | null = await redisGetAsync(`popular_directions_${origin}`)
console.log(`Get populars from cache took ${Math.round(performance.now() - perf)}ms`)
```

I started testing with ApacheBench command `./ab -k -c 100 -n 100 http://localhost:3000/` (means "make hundred requests with 100 concurrency"). Test was running on laptop with i5-8250 (4c/8t), 8GB RAM (DDR4-1600) and NVMe drive (only 10 first entries includes):
```
Get populars from cache tooks 2ms
Get populars from cache tooks 5ms
Get populars from cache tooks 60ms
Get populars from cache tooks 60ms
Get populars from cache tooks 61ms
Get populars from cache tooks 41ms
Get populars from cache tooks 45ms
Get populars from cache tooks 47ms
Get populars from cache tooks 48ms
Get populars from cache tooks 48ms
```

As you can see third request already was executed 30x times (!) slower than the first one! Okay, maybe 60ms is not such a huge value. Let's see what happens on 1000 concurrent users:
```
Get populars from cache tooks 459ms
Get populars from cache tooks 460ms
Get populars from cache tooks 463ms
Get populars from cache tooks 464ms
Get populars from cache tooks 465ms
Get populars from cache tooks 465ms
Get populars from cache tooks 466ms
Get populars from cache tooks 466ms
Get populars from cache tooks 466ms
Get populars from cache tooks 467ms
Get populars from cache tooks 467ms
Get populars from cache tooks 467ms
```

The first thing I did when I saw those numbers I googled for some tips that might help me to understand and improve performance. There was an artice about redis-benchmark. Since I can't run `redis-benchmark` on my WSL (Windows Subsystem for Linux) for some reason, I did it on my VPS (1 core, 2.2Ghz and 2 gigs of RAM) and the results for `GET` operation was ~34k per second. Imagine what the results could be if I'd run this benchmark on my multicore laptop? But there is no difference in performance between 4c/8t and 1c/1t processors.

I tried to increase `somaxconn` in WSL and `tcp_backlog` in Redis config but it seems like this is not redis-server issue. I'd rather think there's an issue with my code or with `node-redis` code.

Is there anything I can try to do to improve `redisGetAsync` performance?

**Comment by stockholmux** [comment] 2019-12-12 21:55
Can you post a reproducible issue here? Obviously since your snippet doesn't include what framework you're using, I can't reproduce the ApacheBench test. Also, it would be nice if it wasn't in typescript :)

Also, I don't know the value of your key, so I don't know how large it is. 

The numbers do look wrong - I've easily got 60k ops/sec against a single node instance and single redis instance, but it kinda looks like the measurement isn't correct.

Another thing to take into consideration is that Node, Redis and ApacheBench are all single threaded. I'm not sure how that behaves in WSL (also - it wouldn't matter on your multicore laptop, unless you're running a cluster of Redis).

**Comment by JamesJGoodwin** [comment] 2019-12-12 23:13
@stockholmux it's just Express.js and Redis. I'm not sure if it's going to work right away, I just copied parts of code out of my project, but it's pretty simple anyway. The value of my key can be found in [sample.zip](https://github.com/NodeRedis/node_redis/files/3958146/sample.zip)



```javascript
const express = require('express')
const Redis = require('redis')
const { promisify } = require('util')
const { performance } = require('perf_hooks')

const app = express()
const redis = Redis.createClient()
const redisGetAsync = promisify(redis.get).bind(redis)

app.get('/', async (req, res) => {
    const perf = performance.now()
    const data = await redisGetAsync(`populars`)
    res.set('Content-Type': 'application/json').send(data)
    console.log(`Get populars from cache tooks ${Math.round(performance.now() - perf)}ms`)
})

app.listen(3000, 'localhost', function() {
    console.log('\x1b[32m%s\x1b[0m', `Server started`)
})
```

> it kinda looks like the measurement isn't correct

I'm not an expert in the questions of performance measurement but isn't it just the easiest way to do so? :) I get unix timestamp before and after an operation and them compare them. Also ApacheBench seems to acknowledge this numbers (plus ~200ms for my internal data processing and Express.js respondings)

```
Percentage of the requests served within a certain time (ms)
  50%     99
  66%    128
  75%    224
  80%    287
  90%    608
  95%    614
  98%    660
  99%    664
 100%    669 (longest request)
```

**Comment by stockholmux** [comment] 2019-12-13 22:07
From your code I got:

```
Get populars from cache tooks 9ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 15ms
Get populars from cache tooks 15ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 13ms
Get populars from cache tooks 12ms
Get populars from cache tooks 11ms
Get populars from cache tooks 10ms
Get populars from cache tooks 10ms
Get populars from cache tooks 10ms
Get populars from cache tooks 10ms
Get populars from cache tooks 10ms
Get populars from cache tooks 10ms
Get populars from cache tooks 10ms
Get populars from cache tooks 11ms
Get populars from cache tooks 11ms
Get populars from cache tooks 11ms
Get populars from cache tooks 11ms
Get populars from cache tooks 12ms
Get populars from cache tooks 12ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 15ms
Get populars from cache tooks 15ms
Get populars from cache tooks 15ms
Get populars from cache tooks 16ms
Get populars from cache tooks 16ms
Get populars from cache tooks 22ms
Get populars from cache tooks 22ms
Get populars from cache tooks 22ms
Get populars from cache tooks 22ms
Get populars from cache tooks 23ms
Get populars from cache tooks 23ms
Get populars from cache tooks 24ms
Get populars from cache tooks 24ms
Get populars from cache tooks 25ms
Get populars from cache tooks 25ms
Get populars from cache tooks 25ms
Get populars from cache tooks 25ms
Get populars from cache tooks 25ms
Get populars from cache tooks 26ms
Get populars from cache tooks 26ms
Get populars from cache tooks 27ms
Get populars from cache tooks 27ms
Get populars from cache tooks 28ms
Get populars from cache tooks 28ms
Get populars from cache tooks 28ms
Get populars from cache tooks 28ms
Get populars from cache tooks 28ms
Get populars from cache tooks 28ms
Get populars from cache tooks 28ms
Get populars from cache tooks 28ms
Get populars from cache tooks 9ms
Get populars from cache tooks 9ms
Get populars from cache tooks 10ms
Get populars from cache tooks 10ms
Get populars from cache tooks 10ms
Get populars from cache tooks 10ms
Get populars from cache tooks 10ms
Get populars from cache tooks 10ms
Get populars from cache tooks 10ms
Get populars from cache tooks 10ms
Get populars from cache tooks 11ms
Get populars from cache tooks 11ms
Get populars from cache tooks 11ms
Get populars from cache tooks 11ms
Get populars from cache tooks 11ms
Get populars from cache tooks 11ms
Get populars from cache tooks 11ms
Get populars from cache tooks 11ms
Get populars from cache tooks 11ms
Get populars from cache tooks 12ms
Get populars from cache tooks 12ms
Get populars from cache tooks 12ms
Get populars from cache tooks 12ms
Get populars from cache tooks 12ms
Get populars from cache tooks 12ms
Get populars from cache tooks 12ms
Get populars from cache tooks 12ms
Get populars from cache tooks 12ms
Get populars from cache tooks 12ms
Get populars from cache tooks 13ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 14ms
Get populars from cache tooks 13ms
Get populars from cache tooks 13ms
Get populars from cache tooks 12ms
```

Which is slower than I would expect (I suspect the Node.js single threaded-ness vs ApacheBench concurrency), however it doesn't have that strange building response time that your seeing. 

ApacheBench is showing for me something very different as well. 
```
Percentage of the requests served within a certain time (ms)
  50%     51
  66%     64
  75%     66
  80%     67
  90%     70
  95%     73
  98%     73
  99%     73
 100%     73 (longest request)
```

This points to some thing strange in your environment. I should note that I also tried [`console.time`](https://nodejs.org/api/console.html#console_console_time_label) and [`console.timeEnd`](https://nodejs.org/api/console.html#console_console_timeend_label) and it seemed to give overall lower numbers than the `performance.now` measurements. 

I'm going to close this since it seems to be a non-library related issue, but feel free to keep responding.

**Closed by stockholmux** 2019-12-13 22:07 UTC
