### ISSUE TITLE
Unable to recover from ECONNREFUSED 

### ISSUE THREAD

**Issue by alexellis** [NodeRedis/node_redis#947] opened 2016-01-06 12:59 UTC
I would like to increment a value with redis - but if the service is not running, I want to log the error and continue. I've tried using on('error') but this gets called in a loop and I can't exit the callback.

Can someone explain how this error is supposed to be handled? I've also looked at max_attempts =1 as an option but this doesn't work.

Node: 0.12.9
node-redis: latest

**Comment by BridgeAR** [comment] 2016-01-07 12:57
Duplicate of #905 

node_redis expects Redis to be available. If this is not the case it tries to reconnect until it's connected or a timeout / max attempt has been reached. Every reconnect failure is going to return an error right now. In my opinion this is nothing bad as I want my Redis instance to be alive. 

So you can log every reconnect failure attempt. As people complaint about it, I'm going to rework this at some point.

I'm a bit confused though that you call on('error') in a loop. The handler should be attached once and not added all over again? Would you be so kind and show some code, so I'm able to better suggest a solution for right now?

**Closed by BridgeAR** 2016-01-07 12:57 UTC

**Comment by alexellis** [comment] 2016-01-07 13:00
I know you have closed this issue, but I am still left wanting. 

Can you provide an equivalent of a try/catch or code example where I can accept a failure without having to handle an exception at the application level?

I also mentioned that max_attempts =1 in the options object had no effect on the amount of retries performed.

**Comment by alexellis** [comment] 2016-01-07 13:03
function keys () {
  this.client = redis.createClient(/* etc */)
}

keys.prototype.setNotified(host, newValue, callback) {
 /* that.client.hset... etc */
};


// If redis not avaiable, do not crash express... ?

var keyStore = new keys();
keyStore.setNotified("some_host", true);

**Comment by BridgeAR** [comment] 2016-01-07 13:17
Do you use `node-redis` or `node_redis`? Because this is node_redis ;)

As far as I understand you, NodeJS crashes, because the on('error') handler is missing. Therefor the max_attempts won't help either, because it'll just prevent more reconnection attempts.

The client in your keys class (I suggest using Keys instead as Name to signal it's a class) does not have a error handler.
So it should look like this instead:

```js
function Keys () {
    this.client = redis.createClient();
    this.client.on('error', function (err) {
        // do stuff with errors
    });
}
```

**Comment by alexellis** [comment] 2016-01-07 14:16
I think I may have referenced node-redis instead meaning to put *node_redis*. With your version of the library (confusing as there are 3 on NPM which are API-compatible) it does seem to handle the error and let me continue working in the example.
