### ISSUE TITLE
redis fails to get string value in websocket ping() function

### ISSUE THREAD

**Issue by zt9** [NodeRedis/node_redis#737] opened 2015-04-12 04:38 UTC
I do a simple redis get string in the following code, but it does not seem to execute the print  function (or even if I replace it with a call back). The `redis.get` is used in other places and it works fine, so not sure what is special about this.. I am using the get when you get a websocket ping..

    var WebSocketServer = require('ws').Server
    var wss = new WebSocketServer({
        port: 8080
    });
    var redis = redis_server.createClient(6379, 'localhost');

    wss.on('connection', function(ws) {
        ws_auth(redis, ws, function(authresult, uid) {
            if (!authresult) {
                console.log(getDateTime() + ': Client %s is not logged', uid);
                ws.close();
                return;
            }
            ws.on('ping', function(data, flags) {
                console.log('pong')
                var cookie = ws.upgradeReq.headers.cookie;
                cookie_json = JSON.parse(cookie);
                console.log(redis.connected);
                redis.get("session:7t2vnajty5y0mvdwc6ly10zcpp8fzyub", redis.print);
            });
            console.log('pong2')
        });
    });
    
I have checked the `session:7t2vnajty5y0mvdwc6ly10zcpp8fzyub` exists in redis.

I have enabled debug and here is the output of the above code:

    pong
    true
    send localhost:6379 id 1: *2
    $3
    get
    $40
    session:7t2vnajty5y0mvdwc6ly10zcpp8fzyub
    
    send_command buffered_writes: 0  should_buffer: false
    send localhost:6379 id 1: *2
    $3
    get
    $42
    "session:7t2vnajty5y0mvdwc6ly10zcpp8fzyub"
    
    send_command buffered_writes: 0  should_buffer: false
    pong2
    
I run redis-cli in monitor mode, I do not even see a command come through.. I have replaced the get with other strings and same result. I cannot believe this is a bug, rather I am missing something?? I am new to node, but I do not think there is any async issue going on. I'd be grateful for any suggestions on how to debug this - I am at the end of my road right now.

**Comment by brycebaril** [comment] 2015-04-12 05:52
Hi @zt9 -- I'm a little puzzled for sure, I expect to see the reply in debug mode for sure, even though I think there's an error in your `redis.get` call it gets sent, but the server should reply.

`redis.get("session:7t2vnajty5y0mvdwc6ly10zcpp8fzyub", redis.print);`

The client instance (`redis`) in your code doesn't have a `print` property, the one you're looking on is on the exported object (`redis_server` in your code)

I.e. `redis.get("session:7t2vnajty5y0mvdwc6ly10zcpp8fzyub", redis_server.print);`

Even though, with `debug_mode` on you should still see something like:

```
net read 127.0.0.1:6379 id 1: $5
HELLO
no callback for reply: HELLO
```

Is the output truncated perhaps?

How about trying just this:

```js
var redis = require("redis");
var client = redis.createClient(6379, "localhost");
redis.debug_mode = true;

client.get("session:7t2vnajty5y0mvdwc6ly10zcpp8fzyub", redis.print);
```

**Comment by zt9** [comment] 2015-04-12 14:08
@brycebaril: thanks for the reply. That get command seems to work outside the web socket loop.
I ran the following:

    var redis = require("redis");
    var client = redis.createClient(6379, "localhost");
    redis.debug_mode = true;
    client.get("test", redis.print);
and I got the following results:

    Sending offline command: get
    send localhost:6379 id 1: *2
    $3
    get
    $4
    test
    
    send_command buffered_writes: 0  should_buffer: false
    net read localhost:6379 id 1: $3
    123
    
    Reply: 123
   
Here is the the same command inside a ws loop that is run through the following code:

    var WebSocketServer = require('ws').Server
    var wss = new WebSocketServer({
        port: 8080
    });
    var redis = redis_server.createClient(6379, 'localhost');

    wss.on('connection', function(ws) {

        ws_auth(redis, ws, function(authresult, uid) {
            if (!authresult) {
                console.log(getDateTime() + ': Client %s is not logged', uid);
                ws.close();
                return;
            }

            ws.on('ping', function(data, flags) {
                console.log('pong')
                var cookie = ws.upgradeReq.headers.cookie;
                cookie_json = JSON.parse(cookie);
                console.log(redis.connected);
                redis.get("test", redis_server.print);
                console.log('pong2')
            });
        });
    });

and I get the following:

    send_command buffered_writes: 0  should_buffer: false
    pong
    true
    send localhost:6379 id 1: *2
    $3
    get
    $4
    test
    
    send_command buffered_writes: 0  should_buffer: false
    pong2
    
    Besides the `send_command buffered_writes` output, I do not see `net read localhost:6379 id 1: $3` being printed out within the ws loop.

**Comment by BridgeAR** [comment] 2015-09-23 23:03
@zt9 would you be so kind and check if this error persists in v.2? That would be a lot of help! :)

**Comment by zt9** [comment] 2015-09-24 02:21
@BridgeAR Hi Ruben, I have moved on from this project and will not be able to check on this anytime soon unfortunately. Wanted to reply back and just not ignore your message. If something changes, I'll update the thread.

**Comment by mnylen** [comment] 2015-10-28 21:43
I'm experiencing similar issue with version 2.2.5 (using node 4.2.1, but also 0.12.7). Sometimes (every 10th try or so) redis.get just doesn't call the provided callback for a long time. It can take over a minute for a simple null reply to get back.

I've been able to reproduce this only with the javascript parser. With hiredis package installed, it seems to always work. It also seems to only occur when connecting to redis running in docker container inside boot2docker virtual machine on OS X, not when connecting to redis instance running on localhost

Plus seems to only happen when the key does not exists beforehand (i.e. I should be getting a null reply). When the key exists, it works all the time.

Redis' SLOWLOG doesn't contain anything during or after the hangup and MONITOR only shows the GET command, but no reply.

During the hangup, I can use redis-cli to issue the same GET command without issues and get instant reply.

redis.get returns true in this case. I tried wrapping it in try..catch and there wasn't nothing. There aren't even any events fired (at least, not the ones mentioned in documentation).

With debug_mode I get this output when this occurs:

```
Send dockerhost:45101 id 1: *2
$3
get
$61
api_1.0.0_loadUutisvahtiList_9a51bd4699884f89cdb69982dd096eb6

```

Hopefully this helps with solving the issue.

**Comment by BridgeAR** [comment] 2015-10-28 22:49
@mnylen your issue is a duplicate of #875 and is already resolved on the latest master. I'll release a new version soon

**Comment by mnylen** [comment] 2015-10-29 05:01
@BridgeAR, nice! Using hiredis should fix this until the new release, right?

**Comment by BridgeAR** [comment] 2015-10-29 07:09
@mnylen yes, using the hiredis parser solved the issue.

**Comment by BridgeAR** [comment] 2016-06-03 17:35
Closing this as I'm pretty sure there is no issue with node_redis anymore if there was one.

**Closed by BridgeAR** 2016-06-03 17:35 UTC
Labels: Help wanted, pending-author-input
