### ISSUE TITLE
ETIMEDOUT when nodejs is idle for awhile(even if set socket_keepalive = true) 

### ISSUE THREAD

**Issue by fanbinghuadev** [NodeRedis/node_redis#1390] opened 2018-11-15 09:09 UTC
Node.js version = v8.12.0
node_redis version = up to date

issue:
in node v8.12.0,i'm getting this error after the nodejs has had no need for redis for a couple hours.But,in node v8.11.1,i don't found issues such so.Is it seem nodejs issue?

**Comment by amanshu-kataria** [comment] 2018-11-15 11:04
I'm also getting the same issue.

**Comment by fanbinghuadev** [comment] 2018-11-15 12:55
I have found the reason. when "socket.setKeepAlive([enable][, initialDelay])" called, "initialDelay" is not set.Set initialDelay (in milliseconds) to set the delay between the last data packet received and the first keepalive probe. Setting 0 for initialDelay will leave the value unchanged from the default (or previous) setting.

**Comment by fanbinghuadev** [comment] 2018-11-15 12:59
Essentially,it is affected by "tcp_keepalive_time" set.

**Comment by stockholmux** [comment] 2018-12-03 20:45
@orhankutlu @fanbinghuadev and @amanshu-kataria Can you give me some info on your setup? Running Redis locally? Version, etc?

I can't seem to recreate. Would be easy enough to setup an option but I'm trying to determine if it should be default.

**Comment by fanbinghuadev** [comment] 2018-12-04 06:14
I added "client.stream.setKeepAlive(true, 60000);" can solve this issue. @orhankutlu @stockholmux

**Comment by stockholmux** [comment] 2018-12-04 14:19
@fanbinghuadev That should work, but it's a band-aid solution and you'll need to do this everytime you re-connect. 

I'd like to get to the root of the problem - I can't personally recreate this - if you would please let me know how you're running Redis, I can fix the problem at a higher level.

**Comment by stockholmux** [comment] 2018-12-06 14:04
#1396 should fix allow for this fix. You can specify a `initalDelay` for the client. 

I've taken a look at the node.js net source between 8.11 and 8.12 and I see no real difference between the two as it comes to the keepAlive mechanism.  Additionally, there is no rational/universal default here, so it's up to you.

I suspect that the root cause is not 8.11 or 8.12 but some vendor or infrastructure provider brutally closing connections, but the initial delay should work around this issue.

**Closed by stockholmux** 2018-12-06 14:04 UTC

**Comment by Fundebug** [comment] 2019-05-09 03:34
@fanbinghuadev I solved the problem by using your method:

```javascript
client.on('connect', function () {
    var socket = client.stream
    socket.setKeepAlive(true, 30 * 1000)
})
```

However, I found that idle redis connection will be disconnected every 2 hours, which is not 1 hour. But I'm not sure about the reason behind it.

**Comment by k1r0s** [comment] 2023-10-16 09:32
After connecting, client.stream is undefined. Whats the problem?
