### ISSUE TITLE
Command callbacks no longer called once `client.closed` is set

### ISSUE THREAD

**Issue by bminer** [NodeRedis/node_redis#791] opened 2015-08-12 15:59 UTC
Consider the following code:

```javascript
var client = require("redis").createClient();
// sometime later...
client.quit();
client.get("foo", function(err) {
    console.log("This callback will never get called");
});
```

In this case, the `client` is trying to be used after the connection has ended.  This should cause the command's callback to be called with an Error.

Perhaps `enable_offline_queue` should be disabled whenever `client.quit()` or `client.end()` is called?  Thoughts?

**Comment by BridgeAR** [comment] 2015-09-04 23:42
Should get fixed by #572

**Comment by BridgeAR** [comment] 2015-09-05 11:33
@bminer I can't reproduce this behavior would you mind writing a failing test for it?

**Comment by bminer** [comment] 2015-09-15 13:47
@BridgeAR - This behavior can be reproduced in node redis 1.0.0.

Here's some code:

```javascript
var client = require("redis").createClient()
	, assert = require("assert")
	, shouldBeSet = false;
client.quit();
setTimeout(function() {
	client.get("foo", function(err) {
		// This callback will never get called
		shouldBeSet = true;
	});
}, 100);
setTimeout(function() {
	assert.ok(shouldBeSet);
}, 1000);
```

**Comment by BridgeAR** [comment] 2015-09-15 23:19
@bminer thx a lot! I should have read your original message more closely :)

Fix is incoming.

**Closed** 2015-09-16 03:43 UTC
Labels: bug, fix-in-progress

**Comment by bminer** [comment] 2015-09-21 15:36
@BridgeAR - Thank you!  I'm excited for the next release.
