### ISSUE TITLE
Invalid opts.uri kills Node.js process

### ISSUE THREAD

**Issue by lukechilds** [NodeRedis/node_redis#1257] opened 2017-07-15 14:45 UTC
Invalid URL provided in opts.url kills Node.js process. Interestingly, when an invalid connection string is passed directly into the constructer it's handled properly.

e.g:

```js
redis.createClient('foo'); // Handled gracefully, emits connection error
redis.createClient({ url: 'foo' }); // Kills Node.js
```

CLI output:
```
$ node -e "require('redis').createClient({ url: 'foo' })"
/Users/lukechilds/.nvm/versions/node/v8.1.2/bin/node[84258]: ../src/pipe_wrap.cc:187:static void node::PipeWrap::Connect(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [/Users/lukechilds/.nvm/versions/node/v8.1.2/bin/node]
 2: node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, double, double) [/Users/lukechilds/.nvm/versions/node/v8.1.2/bin/node]
 3: node::PipeWrap::Connect(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/lukechilds/.nvm/versions/node/v8.1.2/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/Users/lukechilds/.nvm/versions/node/v8.1.2/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/lukechilds/.nvm/versions/node/v8.1.2/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/lukechilds/.nvm/versions/node/v8.1.2/bin/node]
 7: 0x3f77cdf0437d
 8: 0x3f77ce0feb37
zsh: abort      node -e "require('redis').createClient({ url: 'foo' })"
```

Using node_redis 2.7.1, Redis 3.2.6, Node.js 8.1.2 (also tested 7) on OS X.

**Comment by BridgeAR** [comment] 2017-07-20 12:24
Duplicate of #1245. I fixed that in Node 8 and I am backporting it to Node 6 right now but this should also be handled in node_redis itself, so thanks a lot for your PR. I am going to merge it as soon as the I is green (I restarted the job).

**Closed by BridgeAR** 2017-07-20 12:24 UTC
