### ISSUE TITLE
Plan for cluster support

### ISSUE THREAD

**Issue by SeongJongJeon** [NodeRedis/node_redis#922] opened 2015-11-20 09:51 UTC
Is there any plan for cluster support?
Redis 3 has been stable version

**Comment by BridgeAR** [comment] 2015-11-20 10:19
Duplicate of #574. I would like to add cluster support, but I do not have the time right now to do it on my own. Please use https://github.com/gosquared/redis-clustr in the meanwhile.

**Closed by BridgeAR** 2015-11-20 10:19 UTC
Labels: duplicate, Feature Request

**Comment by geoyws** [comment] 2018-03-28 07:15
It's been 3 years and still no cluster support... :(
